#ifndef CPU_HPP
#define CPU_HPP

#define CPU_MSP_ACTIVE (0 << 1)
#define CPU_PSP_ACTIVE (1 << 1)

#define CPU_THREAD_PRIVILEGED (0 << 0)
#define CPU_THREAD_UNPRIVILEGED (1 << 0)

#define CPU_MODE_KERNEL (CPU_PSP_ACTIVE | CPU_THREAD_PRIVILEGED)
#define CPU_MODE_USER (CPU_PSP_ACTIVE | CPU_THREAD_UNPRIVILEGED)

#endif